// <auto-generated />
namespace PocoGenerator.Base
{
    using PocoGenerator.Base.Common;
    public class Vehicle{
        
        [DataObjectFieldAttribute(true, true, false)]
        public System.Int32 VehicleId
        {
            get; set;
        }
        
        public System.String Name
        {
            get; set;
        }
        
        public System.Int32 VehicleTypeId
        {
            get; set;
        }
    }
}
