using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PocoGenerator.Base.CodeGenerator
{
    using System.CodeDom.Compiler;
    using System.Globalization;
    using System.IO;

    using PocoGenerator.Base.Models;

    /// <summary>
    /// The poco code generator.
    /// </summary>
    public class PocoCodeGenerator : ICodeGenerator
    {
        #region Implementation of ICodeGenerator

        /// <summary>
        /// The code writer.
        /// </summary>
        /// <param name="namespace">
        /// The namespace.
        /// </param>
        /// <param name="nameofClass">
        /// The nameof class.
        /// </param>
        /// <param name="fieldDetailses">
        /// The field detailses.
        /// </param>
        /// <returns>
        /// The <see cref="string"/>.
        /// </returns>
        public string CodeWriter(string @namespace, string nameofClass, IEnumerable<FieldDetails> fieldDetailses)
        {
            using (var stringWriter = new StringWriter(CultureInfo.InvariantCulture))
            {
                using (var writer = new IndentedTextWriter(stringWriter))
                {
                    writer.WriteLine("// <auto-generated />");

                    WriteClassStart(@namespace, nameofClass, writer);
                    foreach (var field in fieldDetailses)
                    {
                        WriteProperty(field.Name, field.TypeName.FullName, writer, field.IsPrimaryKey);
                    }

                    WriteClassEnd(@namespace, writer);
                }

                return stringWriter.ToString();
            }
        }

        /// <summary>
        /// The write property.
        /// </summary>
        /// <param name="name"> The name. </param>
        /// <param name="value"> The value. </param>
        /// <param name="writer"> The writer. </param>
        /// <param name="isPrimaryKey"> The is primary key. </param>
        public static void WriteProperty(string name, string value, IndentedTextWriter writer, bool isPrimaryKey = false)
        {
            writer.WriteLine();
            if (isPrimaryKey)
            {
                writer.WriteLine("[DataObjectFieldAttribute(true, true, false)]");
            }

            writer.Write("public ");
            writer.Write(value);
            writer.Write(" ");
            writer.WriteLine(name);
            writer.WriteLine("{");
            writer.Indent++;
            writer.Write("get; set;");
            writer.Indent--;
            writer.WriteLine();
            writer.WriteLine("}");
        }

        /// <summary>
        /// Generates a namespace, using statements and class definition.
        /// </summary>
        /// <param name="namespace">
        /// Namespace that code should be generated in. 
        /// </param>
        /// <param name="className">
        /// Name of the class that should be generated. 
        /// </param>
        /// <param name="writer">
        /// Text writer to add the generated code to. 
        /// </param>
        public static void WriteClassStart(string @namespace, string className, IndentedTextWriter writer)
        {
            if (!string.IsNullOrWhiteSpace(@namespace))
            {
                writer.Write("namespace ");
                writer.WriteLine(@namespace);
                writer.WriteLine("{");
                writer.Indent++;
            }

            writer.WriteLine("using PocoGenerator.Base.Common;");
            writer.Write("public ");
            writer.Write("class ");
            writer.Write(className);
            writer.WriteLine("{");
            writer.Indent++;
        }

        /// <summary>
        /// Generates the closing code for a class that was started with WriteClassStart.
        /// </summary>
        /// <param name="namespace"> Namespace that code should be generated in. </param>
        /// <param name="writer"> Text writer to add the generated code to. </param>
        public static void WriteClassEnd(string @namespace, IndentedTextWriter writer)
        {
            writer.Indent--;
            writer.WriteLine("}");

            if (!string.IsNullOrWhiteSpace(@namespace))
            {
                writer.Indent--;
                writer.WriteLine("}");
            }
        }

        #endregion
    }
}
