// <auto-generated/>
// Guids.cs
// MUST match guids.h
using System;

namespace Company.PocoGenerator
{
    using System.Diagnostics.CodeAnalysis;

    /// <summary>
    /// The guid list.
    /// </summary>
    public static class GuidList
    {
        /// <summary>
        /// The guid poco generator pkg string.
        /// </summary>
        public const string guidPocoGeneratorPkgString = "69e1f1e5-d937-4a65-8e04-c1b8b4f9d89d";

        /// <summary>
        /// The guid poco generator cmd set string.
        /// </summary>
        public const string guidPocoGeneratorCmdSetString = "1663ade8-3ef3-46c7-a138-0fddc981e506";

        /// <summary>
        /// The guid tool window persistance string.
        /// </summary>
        public const string guidToolWindowPersistanceString = "e1134778-7449-48d9-b269-d999c01d2a06";

        /// <summary>
        /// The guid poco generator cmd set.
        /// </summary>
        public static readonly Guid guidPocoGeneratorCmdSet = new Guid(guidPocoGeneratorCmdSetString);
    }
}